version: 2.1

orbs:
  python: circleci/python@3.3.0

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - run:
          name: Install dependencies from pyproject.toml
          command: |
            pip install .
            pip install .[dev]
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
